from typing import Protocol, Any, Iterable


class Notifier(Protocol):
    async def send_to_conn(self, conn_id: str, payload: dict[str, Any]) -> None: ...
    async def broadcast(
        self, conn_ids: Iterable[str], payload: dict[str, Any]
    ) -> None: ...


class RoomStore(Protocol):
    async def create_room(self, room_id: str, room_name: str) -> None: ...
    async def get_room_name(self, room_id: str) -> str | None: ...

    async def add_conn(
        self,
        room_id: str,
        conn_id: str,
        nickname: str | None = None,
        ready: bool = False,
    ) -> None: ...
    async def remove_conn(self, room_id: str, conn_id: str) -> None: ...
    async def list_conns(self, room_id: str) -> set[str]: ...

    async def set_ready(self, room_id: str, conn_id: str, ready: bool) -> None: ...
    async def get_lobby_state(self, room_id: str) -> dict[str, Any] | None: ...

    async def set_game_state(self, room_id: str, state: str) -> None: ...
    async def get_game_state(self, room_id: str) -> str | None: ...
    async def end_game(
        self, room_id: str, result: dict[str, Any] | None = None
    ) -> dict[str, Any]: ...

    async def issue_resume_token(self, room_id: str, conn_id: str) -> str: ...
    async def consume_resume_token(self, token: str) -> dict[str, Any]: ...
