from impostor.domain.models import Room


class Notifier(Protocol):
    async def send_to_conn(self, conn_id: str, payload: dict[str, Any]) -> None: ...
    async def broadcast(
        self, conn_ids: Iterable[str], payload: dict[str, Any]
    ) -> None: ...


class RoomStore(Protocol):
    async def create_room(
        self, room_id: str, room_name: str, settings: RoomSettings
    ) -> None: ...
    async def get_room(self, room_id: str) -> Room | None: ...
    async def update_room(self, room_id: str, **kwargs) -> None: ...
    async def delete_room(self, room_id: str) -> None: ...

    async def add_conn(
        self, room_id: str, conn_id: str, nickname: str | None = None
    ) -> None: ...
    async def remove_conn(self, room_id: str, conn_id: str) -> None: ...
    async def list_conns(self, room_id: str) -> set[str]: ...
    async def get_conn_nickname(self, conn_id: str) -> str | None: ...
